{
 "title": "Метрики приложения",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/\"}[1m])",
     "legendFormat": "rps /"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/predict-bank-quality\"}[1m])",
     "legendFormat": "rps_predict"
    }
   ]
  },
  {
   "title": "cpu seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время ответа ручек",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ml_model_response_time_sum[1m]) / rate(ml_model_response_time_count[1m])",
     "legendFormat": "ml_model_response_time"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/predict-bank-quality\"}[1m]) / rate(http_request_duration_seconds_count{handler=\"/predict-bank-quality\"}[1m])",
     "legendFormat": "general_response_time"
    },
    {
     "expr": "rate(collect_features_response_time_sum[1m]) / rate(collect_features_response_time_count[1m])",
     "legendFormat": "collect_features_time"
    }
   ]
  }
 ]
}